---
- hosts: all
  serial: 2
  tasks:
    - name: Checking for pending updates
      command: /usr/lib/update-notifier/apt-check --package-names
      register: packages
      changed_when: packages.stderr != ""

    - name: update, upgrade, autoremove
      become: yes
      apt: 
        update_cache: yes
        upgrade: full
        autoremove: yes
      when: packages.stderr != ""

    - name: Check if a reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required
      changed_when: reboot_required.stat.exists

    - name: Reboot system if required
      become: yes
      reboot:
        reboot_timeout: 900
      when: reboot_required.stat.exists == true
      register: restart_status